/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicacaoIdRouteImport } from './routes/indicacao.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoIdRoute = IndicacaoIdRouteImport.update({
  id: '/indicacao/$id',
  path: '/indicacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/nova': typeof NovaRoute
  '/perfil': typeof PerfilRoute
  '/indicacao/$id': typeof IndicacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/nova': typeof NovaRoute
  '/perfil': typeof PerfilRoute
  '/indicacao/$id': typeof IndicacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/nova': typeof NovaRoute
  '/perfil': typeof PerfilRoute
  '/indicacao/$id': typeof IndicacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/nova' | '/perfil' | '/indicacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/nova' | '/perfil' | '/indicacao/$id'
  id: '__root__' | '/' | '/admin' | '/nova' | '/perfil' | '/indicacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  NovaRoute: typeof NovaRoute
  PerfilRoute: typeof PerfilRoute
  IndicacaoIdRoute: typeof IndicacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao/$id': {
      id: '/indicacao/$id'
      path: '/indicacao/$id'
      fullPath: '/indicacao/$id'
      preLoaderRoute: typeof IndicacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  NovaRoute: NovaRoute,
  PerfilRoute: PerfilRoute,
  IndicacaoIdRoute: IndicacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
